import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased py-5 m-0 flex justify-center w-full">
        <main className="flex-1 mx-0 w-full max-w-[1820px]">{children}</main>
      </body>
    </html>
  );
}
