import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased overflow-hidden h-screen m-0 flex items-center justify-center w-full">
        <main className="flex-1 mx-0 w-full max-w-[1820px] h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
